FORMAT: 1A
HOST: https://api.previo.cz/app

# API - Previo PMS app

## Allowed HTTPs requests:
- `GET` - Get a resource or list of resources
- `POST` - To create resource
- `PUT` - Update resource
- `DELETE` - To delete resource

## Common status codes:
- `200` - success
- `204` - success on DELETE (no content)
- `400` – something's wrong with request (check error message and display to user)
- `401` - missing or invalid authentication
- `5XX` – there's something wrong with server.

## Errors

Every response could return an error. When this happens status code is `4XX` or `5XX` and response body contains JSON formatted response like this:

```
{
    code: 402 (number, required)
    error: Failed to get data from MySQL (string, required)
    message: Failed to get data (string, required)
}
```

##Headers
```
Authorization: {Base64(userEmail:password)}
X-Previo-App-ID: {appId}
X-Previo-Hotel-ID: {hotId}
```

#### X-Previo-App-ID
Identifying which application sends a request
- **`1` - Previo PMS app**


## User [/user]

### Get user info [GET /user{?os}{?versionCode}]

+ Parameters
    + os: ios (string, required) - Operation system (ios. android)
    + versionCode: 33 (number, required) - Code of version aplication

+ Request (application/json)
    + Headers

            Authorization: {Base64(userEmail:password)}
            X-Previo-App-ID: 1

+ Response 200 (application/json)
    + Attributes (UserInfo)


## Reservation [/reservation]

### Get reservation [GET /reservation{?resId}{?comId}]

`In development`

+ Parameters
    + resId: 26345103 (number, optional) - The unique identifier for group reservation
    + comId: 3241 (number, optional) - The unique identifier for reservation commission

+ Request (application/json)
    + Headers

            Authorization: {Base64(userEmail:password)}
            X-Previo-App-ID: 1
            X-Previo-Hotel-ID: {hotId}

+ Response 200 (application/json)
    + Attributes (Reservation)

### Save new reservation [POST]

`In development`

+ Request (application/json)
    + Headers

            Authorization: {Base64(userEmail:password)}
            X-Previo-App-ID: 1
            X-Previo-Hotel-ID: {hotId}

    + Attributes (ReservationCreate)

+ Response 200 (application/json)
    + Attributes (Reservation)

### Update reservation [PUT /reservation{resId}]

`In development`

+ Parameters
    + resId: 11994846 (number, required) - The unique identifier for goup reservation

+ Request (application/json)
    + Headers

            Authorization: {Base64(userEmail:password)}
            X-Previo-App-ID: 1
            X-Previo-Hotel-ID: {hotId}

    + Attributes (Reservation)

+ Response 200 (application/json)
    + Attributes (Reservation)

### Delete commission [DELETE /commission/{?comId}]

`In development`

+ Parameters
    + comId: 11994846 (number, required) - The unique identifier for commission
    
+ Request (application/json)
    + Headers

            Authorization: {Base64(userEmail:password)}
            X-Previo-App-ID: 1
            X-Previo-Hotel-ID: {hotId}

+ Response 204 (application/json)

### Delete reservation [DELETE /reservation/{?resId}]

`In development`

+ Parameters
    + resId: 11994846 (number, required) - The unique identifier for reservation
    
+ Request (application/json)
    + Headers

            Authorization: {Base64(userEmail:password)}
            X-Previo-App-ID: 1
            X-Previo-Hotel-ID: {hotId}

+ Response 204 (application/json)


## Account [/account]

`!! SHOW ALL CAHNGES IN RESERVATION HISTORY !!`

### Get account [GET /account{?resId}]

`In development`

+ Parameters
    + resId: 11994846 (number,required) - The unique identifier for reservation
    
+ Request (application/json)
    
+ Response 200 (application/json)
    + Attributes (Account)

### Add item at account [POST /account{?resId}{?comId}]

`In development`

+ Parameters
    + resId: 11994846 (number,required) - The unique identifier for reservation (add item at group account)
    + comId: 11994846 (number,required) - 12484225 (number,required) - The unique identifier for commission of reservation (add item at room/commission account)
    
+ Request (application/json)
   + Attributes (AccountItem)
   
+ Response 200 (application/json)
    + Attributes (Account)

### Update account [PUT /account{?resId}]

`In development`

+ Parameters
    + resId: 11994846 (number,required) - The unique identifier for reservation
    
+ Request (application/json)
   + Attributes (Account)
   
+ Response 200 (application/json)
    + Attributes (Account)

### Delete item [DELETE /account{?coaId}{?comId}]

`In development`

+ Parameters
    + coaId: 213 - (nuber, required) - The unique identifier for account item

+ Request (application/json)

+ Response 204 (application/json)

    
## Hotel [/hotel]

### Get hotels [GET /hotel]

`In development`

+ Request (application/json)
    
+ Response 200 (application/json)
    + Attributes (array[Hotel])


## Premises [/premise]

### Get list of premise kinds [GET /premise/kind{?obtId}]

`In development`

+ Parameters
    + obtId: 1 (number,required) - The unique identifier for premise type (1 - room, 2 - others)

+ Request (application/json)
    
+ Response 200 (application/json)
    + Attributes (array[PremiseKind])

### Get list of premises [GET /premise{?obtId}]

`In development`

+ Parameters
    + obtId: 1 (number,required) - The unique identifier for premise type (1 - room, 2 - others)

+ Request (application/json)
    
+ Response 200 (application/json)
    + Attributes (array[Premise])

### Get premises with availability in term [GET /premise/availability{?obtId}{?from}{?to}]

`In development`

+ Parameters
    + obtId: 1 (number,required) - The unique identifier for premise type (1 - room, 2 - others)
    + from: `2017-04-12 14:30:00` (string, required) - Date check-in reservation (YYYY-MM-DD'T'HH:mm:ss'Z')
    + to: `2017-04-16 12:30:00` (string, required) - Date check-out reservation (YYYY-MM-DD'T'HH:mm:ss'Z')

+ Request (application/json)
    
+ Response 200 (application/json)
    + Attributes (array[PremiseAvailable])


## Meal [/meal]

### Get list of meals [GET /meal]

`In development`

+ Request (application/json)
    
+ Response 200 (application/json)
    + Attributes (array[Meal])

### Is meal avalible in term [GET /meal{?from}{?to}]

`In development`

+ Parameters
    + from: `2017-04-12T14:30:00Z` (string, required) - Date check-in reservation (YYYY-MM-DD'T'HH:mm:ss'Z')
    + to: `2017-04-16T12:30:00Z` (string, required) - Date check-out reservation (YYYY-MM-DD'T'HH:mm:ss'Z')

+ Request (application/json)
    
+ Response 200 (application/json)
    + Attributes (array[MealAvalible])


## Statistic [/statistic]

### Get dashboard data [GET /statistic/dashboard{?date}]

`In development`

+ Parameters
    + date: `2017-04-12T00:00:00Z` (string, required) - Load dashboatd data for this date (YYYY-MM-DD'T'HH:mm:ss'Z')

+ Request (application/json)
    
+ Response 200 (application/json)
    + Attributes (Dashboard)


## Review [/review]

### Get guests reviews [GET /review{?count}{?offset}]

`In development`

+ Parameters
    + count: 50 (number, optional) - Count of return review
    + offset: 10 (number, optional) - Offset

+ Request (application/json)
    
+ Response 200 (application/json)
    + Attributes (array[Review])


## Suggest [/]

### Get reservations by filter [GET /reservation/suggest{?from}{?to}{?fulltext}{?count}{?offset}]

`In development`

+ Parameters
    + from: `2017-04-12T12:12:30` (string, optional) - Date check-in reservation (ISO 8601)
    + to: `2017-04-16T22:32:12`(string, optional) - Date check-out reservation (ISO 8601)
    + fulltext: Jonh Wick (string, optional) - Search in coucher, contact person by name, phone and email, company name, guest by name, phone and email (required send parametrs count and offset)
    + count: 20 (number, optional) - Count of items in responce array
    + offset: 40 (number, optional) - Offset of first item in array

+ Request (application/json)
    + Headers

            Authorization: {Base64(userEmail:password)}
            X-Previo-App-ID: 1
            X-Previo-Hotel-ID: {hotId}

+ Response 200 (application/json)
    + Attributes (array[ReservationSuggest])

### Contact person [GET /suggest/contactPerson{?fulltext}]

`In development`

+ Parameters
    + fulltext: Jonh Wick (string, optional) - Search in contact person by name, phone and email

+ Request (application/json)
    
+ Response 200 (application/json)
    + Attributes (array[ContactPerson])

### Guest [GET /suggest/guest{?fulltext}]

`In development`

+ Parameters
    + fulltext: Jonh Wick (string, optional) - Search in guest firtname, surname, email and phone

+ Request (application/json)
    
+ Response 200 (application/json)
    + Attributes (array[GuestSuggest])

### Company [GET /suggest/company{?fulltext}]

`In development`

+ Parameters
    + fulltext: SpaceX (string, optional) - Search in company name, IČ, DIČ

+ Request (application/json)
    
+ Response 200 (application/json)
    + Attributes (array[Company])

### Account Items [GET /suggest/accountItems{?fulltext}{?obkId}{?from}{?to}{?curId}]

`In development`

+ Parameters
    + fulltext: vine (string, optional) - Search by query, result is limited when fulltext is empty
    + obkId: 1245 (number, optional) - Premise kind id
    + from: `2014-02-15T00:00:00Z` (string, optional) - Term from in Y-m-d format
    + to: `2018-09-15T00:00:00Z` (string, optional) - Term to in Y-m-d format
    + curId: 1 (number, optional) - Currency id, set to hotel's currency by default
    
+ Request (application/json)
    
+ Response 200 (application/json)
    + Attributes (array[AccountItem])


## System [/system]

### Code books [GET /system/codeBook]

`In development`
            
+ Response 200 (application/json)
    + Attributes (CodeBook)


## Data Structure

## Reservation
+ resId: 71994 (number, required) - The unique identifier for reservation
+ commissions (array[Commission], required)
+ contactPerson (ContactPerson, optional)
+ note: Lorem ipsum dolor sit amet... (string, optional) - Note for the reservations with <b> <i> <u> HTML tags

## Commission
+ comId: 52225 (number, required) - The unique identifier for commission of reservation
+ objId: 6323 (number, required) - The unique identifier for the room
+ prpId: 1 (number, optional) - The unique identifier for Previo partner (Booking.com, Hotel.cz, Expedia.com, ...)
+ cosId: 1 (number, required) - The unique identifier for status of commission
+ voucher: 20130704 (string, optional) - Voucher for commission
+ termFrom: `2018-01-21T10:59` (string, required) - Date check-in reservation (ISO 8601)
+ termTo: `2018-02-03T10:59` (string, required) - Date check-out reservation (ISO 8601)
+ created: `2017-05-23T10:59` (string, required) - Create date of commission (ISO 8601)
+ optionExpiration: `2017-05-23T10:59` (string, optional) - Date of expiration option (ISO 8601)
+ note: Lorem ipsum dolor sit amet... (string, optional) - Note for the commission with <b> <i> <u> HTML tags
+ guests (array[Guest], required)
+ company (Company)

## ReservationCreate
+ commissions (array[CommissionCreate], required)
+ contactPerson (ContactPerson, optional)
+ note: Lorem ipsum dolor sit amet... (string, optional) - Note for the reservations with <b> <i> <u> HTML tags

## CommissionCreate
+ objId: 6323 (number, required) - The unique identifier for the room
+ cosId: 1 (number, required) - The unique identifier for status of commission
+ objId: 6323 (number, required) - The unique identifier for the room
+ termFrom: `2018-01-21T10:59` (string, required) - Date check-in reservation (ISO 8601)
+ termTo: `2018-02-03T10:59` (string, required) - Date check-out reservation (ISO 8601)
+ optionExpiration: `2017-05-23T10:59` (string, optional) - Date of expiration option (ISO 8601)
+ guestCount: 4 (number, required) - Count of guest
+ guestCountWithoutBed: 2 (number, optional) - Count of guest without bed
+ voucher: 20130704 (string, optional) - Voucher for commission
+ note: Lorem ipsum dolor sit amet... (string, optional) - Note for the commission with <b> <i> <u> HTML tags
+ company (Company)

## ReservationSuggest
+ resId: 71994 (number, required) - The unique identifier for reservation
+ commissions (array[CommissionSuggest], required)
+ contactPersonName: Elon Musk (string, optional) - Name of contact person

## CommissionSuggest
+ comId: 643 (number, required) - The unique identifier for commission of reservation
+ cosId: 1 (number, required) - The unique identifier for status of commission
+ termFrom: `2018-01-21T10:59` (string, required) - Date check-in reservation (ISO 8601)
+ termTo: `2018-02-03T10:59` (string, required) - Date check-out reservation (ISO 8601)
+ guestName: Elon Musk (string, optional) - Name of first filled guest
+ guestCount: 3 (number, required) - Count of guest on this room
+ companyName: Previo - Name of company
+ prpId: 1 (number, optional) - The unique identifier for Previo partner (Booking.com, Hotel.cz, Expedia.com, ...)

## Guest
+ gueId: 9366 (number,optional) - The unique identifier for guest per hotel
+ guaId: 1 (number, required) - The unique identifier for guest category
+ meaId: 1 (number, optional) - The unique identifier for guest meal
+ firstName: David (string, optional)
+ lastName: O'Sheen (string, optional)
+ email: user@example.com (string, optional)
+ phone: +420 421 123 987 (string, optional)
+ isRecreation: true (boolean, required) - The guest will pay the city fee
+ recreation: Work trip (string, optional) 
+ birthDate: `2017-05-24T00:00:00` (string, optional) - (ISO 8601)
+ genderId: 1 (number, required) - The unique identifier for guest gender (genId is not allowed!! genderId is from static code book)
+ address (AddressGuest, required)
+ visa: 324ERTCVGHJIU (string, optional)
+ numberPlate: 7A7 2K3S (string, optional) - Number plate of guest`s car
+ identity (Identity, optional)

## GuestSuggest
+ gueId: 34590366 (number,required) - The unique identifier for guest per hotel
+ guaId: 1 (number, required) - The unique identifier for guest category
+ firstName: David (string, optional)
+ lastName: O'Sheen (string, optional)
+ email: radim@vaculik.cz (string, optional)
+ phone: +420 421 123 987 (string, optional)
+ birthDate: `2017-05-24T00:00:00Z` (string, optional) - (YYYY-MM-DD'T'HH:mm:ss'Z') https://cs.wikipedia.org/wiki/ISO_8601
+ genderId: 1 (number, required) - The unique identifier for guest gender (genId is not allowed!! genderId is from static code book)
+ address (AddressGuest, required)
+ visa: 324ERTCVGHJIU (string, optional)
+ numberPlate: 7A7 2K3S (string, optional) - Number plate of guest`s car
+ identity (Identity, optional)

## AddressGuest
+ street: Panska (string, optional)
+ streetNumber: 6 (string, optional)
+ city: Brno (string,optional)
+ zip: 60200 (string,optional)
+ couId: 1 (number,optional) - The unique identifier for country

## ContactPerson
+ name: Elon Musk (string, optional)
+ email: elon.musk@spacex.com (string, optional)
+ phone: +420 340 233 034 (string, optional)

##Company
+ parId: 2412 (number, optional) - The unique identifier for company
+ shortcut: Previo (string, optional)
+ name: Previo s.r.o. (string, optional)
+ address (AddressCompany, required)
+ companyIdentifications (array[CompanyIdentification], required)

## AddressCompany
+ street: Panska (string, optional)
+ streetNumber: 6 (string, optional)
+ city: Brno (string, optional)
+ zip: 60200 (string, optional)
+ couId: 1 (number, required) - The unique identifier for country

## CompanyIdentification
+ value: 233MK2 (string, optional) - Value of IČ, DIČ etc..
+ type: 1 (number, required) - Type of company identification (CompanyIdentificationNumber)

## Identity
+ number: N5646645 (string, optional)
+ guiId: 1 (number, optional) - The unique identifier for guest identity type

## Account
+ curId: 1 (number,required) - The unique identifier for currency
+ commisions (array[CommissionAccount])
+ group (GroupAccount)

## CommissionAccount
+ comId: 12484225 (number,required) - The unique identifier for commission of reservation
+ total: 200.21 (number, required) - Total price af room account
+ accountItems (array[AccountItem])

## GroupAccount 
+ total: 200.21 (number, required) - Total price af room account
+ resId: 11994846 (number,required) - The unique identifier for reservation
+ accountItems (array[AccountItem])

## AccountItem
+ coaId: 213 (number, required) - The unique identifier for account item
+ name: Welness (string, required)
+ count: 2 (number, required) - Count of this items at account
+ price: 20.31 (number, required)
+ vatId: 1 (number, required) - The unique identifier for vat

## Hotel
+ hotId: 14690 (number, required) - The unique identifier for hotel
+ name: Previo hotel (string, required) - Name of hotel
+ licId: 1 (number, required) - The unique identifier for license: 2 - pro, 3 - lite, 4 - connect, 5 - bridge, 7 - school, 8 - eKasa
+ arrival: `14:00:00Z` (string, required) - (HH:mm:ss'Z') Time of default check-in
+ departure: `10:00:00Z` (string, required) - (HH:mm:ss'Z') Time of default check-out
+ defaultCurrency: 1 (number, required) - Default currency for the hotel
+ defaultMeal: 1 (number, required) - Default meal for hotel
+ defaultGuestCategory: 1 (number, required) - Default guset category for the hotel
+ guestCategory (array[GuestCategory])
+ currencies (array[Currency])

## Currency 
+ curId: 1 (number, required) - The unique identifier for currency
+ code: EUR (string, required)

## GuestCategory
+ guaId: 1 (number, required) - The unique identifier for guest category
+ name: Senior (string, required)

## PremiseKind
+ obkId: 2341 (number, required) - The unique identifier for premise kind
+ name: Double (string, required) - Name of object type premise
+ capacity: 3 (number, required) - Number of bed
+ extraCapacity: 2 (number, required) - Number of extra bed
+ count: 6 (number, required) - Total count of premise type

## Premise
+ objId: 6323 (number, required) - The unique identifier for the premise
+ obkId: 2341 (number, required) - The unique identifier for premise kind
+ name: Space (string, required) - Name of the premise

## PremiseAvailable
+ objId: 6323 (number, required) - The unique identifier for the premise
+ hasStop: true (boolean, required) - There is a STOP on the premise in given term
+ isOccupied: true (boolean, required) - There is a reservation/s going on in given term

## PremiseStop
+ objId: 1231 (number, required) - The unique identifier for the premise
+ terms (array[Term]) - List of terms stops at premise

## Term
+ termFrom: `2017-05-21T10:59Z` (string, required) - Start at this date (YYYY-MM-DDTHH:mm:ssZ) https://cs.wikipedia.org/wiki/ISO_8601
+ termTo: `2017-05-21T10:59Z` (string, required) - End at this date (YYYY-MM-DDTHH:mm:ssZ) https://cs.wikipedia.org/wiki/ISO_8601

## UserInfo
+ versionSupported: true (boolean, required) - Is version of aplication supported
+ newerVersion: false (boolean, required) - Is avalible newer version
+ permission (Permission, required) - Listed permissions for users

## Permission
+ modules (ModulePermission, required) - Permission to view the module
+ privileges (Privileges, required) - Permission for each operations

## ModulePermission
+ reservationsCanvas: true (boolean, required) - Permission for view on canvasRemove atribut 
+ search: true (boolean, required) - Permission for search
+ dashboard: true (boolean, required) - Permission for view on dashboard
+ prices: true (boolean, required) - Permission for view into price modul
+ closedRooms: true (boolean, required) - Permission for view into close rooms modul

## Privileges
+ reservations (ReservationPermission, required) - Modify items in reservation by reservation status
+ companies (CompanyPermission, required) - Permission to add/edit/delete companies
+ reviews (ReviewPermission, required) - Permission to edit/delete reviews
+ prices (PricePermission, required) - Permission to edit prices

## ReservationPermission
+ option (ReservationStatusPermission, required) - 
+ confirmed (ReservationStatusPermission, required) - 
+ checkedIn (ReservationStatusPermission, required) - 
+ checkedOut (ReservationStatusPermission, required) - 
+ others (ReservationStatusPermission, required) - 
+ waitingList (ReservationStatusPermission, required) - 
+ cancelled (ReservationStatusPermission, required) - 
+ noShow (ReservationStatusPermission, required) - 

## ReservationStatusPermission
+ add: true (boolean, required) - Permission for adding new reservations
+ edit: true (boolean, required) - Permission for editing reservations
+ editChangeStatus: true (boolean, required) - Permission for changing status
+ editHotelAccountEditItemVatRateEdit: true (boolean, required) - Permission for changing vat value
+ editHotelAccountEditItemPriceEdit: true (boolean, required) - Permission for changing price on room account
+ editHotelAccountItemRemove: true (boolean, required) - Permission for changing deleting items on room account
+ editReservationNoteEdit: true (boolean, required) - Permission for editing reservation note
+ editHotelAccountOwnItemAdd: true (boolean, required) - Permission for adding new item on hotel account

## CompanyPermission
+ add: true (boolean, required) - Permission for add company 
+ edit: true (boolean, required) - Permission for edit company

## ReviewPermission
+ edit: true (boolean, required) - Permission for editing reviews (Reply to reviews)
+ remove: true (boolean, required) - Permission for delete review

## PricePermission
+ edit: true (boolean, required) - Permission for editing price of rooms
+ closedRoomsEdit: true (boolean, required) - Permission for closing/opening rooms for partners (Reservation+, Booking.com, Hotel.cz, atd...)

## PrivilegesDEPRECATED
+ reservation: 3 (number, required) - Permission at reservation
+ managerReports: 1 (number, required) - Permission at  managers reports
+ guestReviews: 1 (number, required) - Permission at guest reviews

## Meal
+ meaId: 1 (number, required) - The unique identifier for meal
+ name: All inclusive (string, required)

## MealAvalible
+ meaId: 1 (number, required) - The unique identifier for meal
+ isAvalible: true (boolean, optional) - Is meal avalible in term

## NotificationSetting
+ newCanvas: true (boolean, required) - Send notification at new reservation from canvas
+ newPartner: false (boolean, required) - Send notification at new reservation from partners (Booking.com, Hotel.cz, Expedia.com, ...)
+ newWeb: true (boolean, required) - Send notification at new reservation from Reservation+
+ cancelCanvas: true (boolean, required) - Send notification at cancel reservation from canvas
+ cancelPartner: false (boolean, required) - Send notification at cancel reservation from partners (Booking.com, Hotel.cz, Expedia.com, ...)
+ cancelWeb: true (boolean, required) - Send notification at cancel reservation from Reservation+
+ userTip: true (boolean, required) - Send notification with user tip (link at web-site)

## Dashboard
+ curId: 1 (number, required) - The unique identifier for currency
+ roomOccupancy: 30 (number, required) - Percent occupancy of rooms
+ bedOccupancy: 25 (number, required) - Percent occupancy of beds
+ revenues: 3234 (number, required) - Revenues for selected date
+ revpar: 532 (number, required) - Revpar for selected date
+ adr: 43 (number, required) - Adr for selected date
+ pickup: 23 (number, required) - Pickup for selected date
+ arrival: 22 (number, required) - Count of arrival reservation at selected date
+ departure: 12 (number, required) - Count of departure reservation at selected date
+ create: 12 (number, required) - Number of created reservation at selected date
+ optionsExpiring: 3 (number, required) - Number of expiration option at selected date
+ revparLastYear: 332 (number, required) - Revpar for same date at last year
+ adrLastYear: 23 (number, required) - Adr for same date at last year

## Review
+ termFrom: `2017-05-21T10:59Z` (string,required) - Date check-in reservation (YYYY-MM-DDTHH:mm:ssZ) https://cs.wikipedia.org/wiki/ISO_8601
+ termTo: `2017-05-23T10:59Z` (string,required) - Date check-out reservation (YYYY-MM-DDTHH:mm:ssZ) https://cs.wikipedia.org/wiki/ISO_8601
+ voucher: 557ER32 (string, required) - Voucher of commission
+ created: `2017-05-23T10:59Z` (string, required) - Date od created review (YYYY-MM-DDTHH:mm:ssZ) https://cs.wikipedia.org/wiki/ISO_8601
+ service: 2 (number, optional) - Services (1 to 10)
+ staff: 10 (number, optional) - Staff (1 to 10)
+ clean: 7 (number, required) - Cleanness (1 to 10)
+ comfort: 2 (number, required) - Comfort (1 to 10)
+ ratio: 4 (number, required) - Price / value ratio (1 to 10)
+ positiveMessage: Good location, and new forniture (string, optional) - Positive text of review
+ negativeMessage: Noisy rooms (string, optional) - Negative text of review
+ privateMessage: Difficult to sleep when the neighbour is watching the tv in a normal volume (string, optional) - Private message to hotel personal
+ guestName: Jonh Wick (string, optional) - Guest name, send NULL if anonym
+ guestCountry: USA (string, optional) - Guest country
+ guestTown: Bejrút (string, optional) - Guest town

## CodeBook
+ commissionStatuses (array[ComissionStatus])
+ partners (array[Partner])
+ countries (array[Country]
+ vats (array[Vat])
+ licences (array[License])
+ companyIdentificationNumbers (array[CompanyIdentificationNumber])

## ComissionStatus
+ cosId: 1 (number, required) - The unique identifier for commission status
+ name: Option (string, required) - Name of reservation status
+ color: #FE8F01 (string, required) - Color for reservation status
+ showOnCanvas: true (boolean, required) - Show reservation on canvas

## Partner
+ prpId: 1 (number, required) - The unique identifier for Previo partner (Booking.com, Hotel.cz, Expedia.com, ...)
+ name: Booking.com (string, optional) - Name of Previo partner
+ logo: https://files.previo.cz/previoPartner/50x50/1.gif (string, required) - URL to partner logo

## Country
+ couId: 1 (number, required) - The unique identifier for country
+ name: Czechia (string, required)

## Vat
+ vatId: 1 (number, required) - The unique identifier for VAT
+ name: 21% DPH (string, required) - Basic rate (string, required)

## License
+ licId: 1 (number, required) - The unique identifier for license
+ name: Pro (string, required) - Name of license

## CompanyIdentificationNumber
+ identificationNumer: 1 (number, required) - The unique identifier for company identification number
+ name: IČ (string, required) - Name of company identification number